# Generated by Django 5.2.17 on 2026-09-18 19:07

import django.db.models.deletion
import django.db.models.manager
import lares.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_household_calendar_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.resource')),
                ('direction', models.CharField(choices=[('borrowed', 'Me lo prestaron'), ('lent', 'Lo presté')], default='borrowed', max_length=10, verbose_name='sentido')),
                ('principal', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='importe original')),
                ('interest_kind', models.CharField(choices=[('none', 'Sin intereses'), ('flat', 'Interés fijo sobre el saldo'), ('amortized', 'Amortizado (cuota fija)')], default='none', max_length=12, verbose_name='intereses')),
                ('annual_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='tasa anual (%)')),
                ('started_on', models.DateField(blank=True, null=True, verbose_name='desde cuándo')),
                ('term_months', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='plazo en meses')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='cuota')),
                ('payment_day', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='día de pago')),
                ('state', models.CharField(choices=[('current', 'Al corriente'), ('late', 'Atrasado'), ('paid', 'Pagado'), ('forgiven', 'Perdonado')], default='current', max_length=12, verbose_name='estado del préstamo')),
                ('is_informal', models.BooleanField(default=False, verbose_name='sin contrato')),
                ('counterpart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='core.party', verbose_name='con quién')),
            ],
            options={
                'verbose_name': 'préstamo',
                'verbose_name_plural': 'préstamos',
            },
            bases=('core.resource',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.UUIDField(default=lares.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('date', models.DateField(db_index=True, verbose_name='cuándo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='cuánto')),
                ('principal_part', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='a capital')),
                ('interest_part', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='a intereses')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='nota')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.household')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='loans.loan')),
            ],
            options={
                'verbose_name': 'abono',
                'verbose_name_plural': 'abonos',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['household', 'loan', '-date'], name='loans_loanp_househo_21677c_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
