# Generated by Django 5.2.17 on 2026-09-18 18:09

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_resource_disposal_amount_resource_disposal_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.resource')),
                ('branch', models.CharField(choices=[('vehicle', 'Automóvil'), ('home', 'Hogar'), ('life', 'Vida'), ('health', 'Gastos médicos'), ('liability', 'Responsabilidad civil'), ('valuables', 'Objetos de valor'), ('other', 'Otro')], default='other', max_length=20, verbose_name='ramo')),
                ('policy_number', models.CharField(blank=True, db_index=True, max_length=60, verbose_name='número de póliza')),
                ('coverage_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='suma asegurada')),
                ('deductible', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='deducible')),
                ('premium', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='prima')),
                ('premium_cycle', models.CharField(choices=[('yearly', 'Anual'), ('semiannual', 'Semestral'), ('quarterly', 'Trimestral'), ('monthly', 'Mensual')], default='yearly', max_length=20, verbose_name='cómo se paga')),
                ('premium_day', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='día de pago')),
                ('starts_on', models.DateField(blank=True, null=True, verbose_name='vigente desde')),
                ('ends_on', models.DateField(blank=True, db_index=True, null=True, verbose_name='vence el')),
                ('beneficiaries', models.CharField(blank=True, max_length=300, verbose_name='beneficiarios')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies_brokered', to='core.party', verbose_name='agente')),
                ('insurer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies_issued', to='core.party', verbose_name='aseguradora')),
            ],
            options={
                'verbose_name': 'póliza',
                'verbose_name_plural': 'pólizas',
            },
            bases=('core.resource',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
