from .base import *  # noqa: F403

DEBUG = False

SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
# SAMEORIGIN, no DENY: el visor de documentos incrusta archivos propios.
X_FRAME_OPTIONS = "SAMEORIGIN"
