# Generated by Django 5.2.17 on 2026-09-18 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_apikey_webhook_webhookdelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='acquired_on',
            field=models.DateField(blank=True, null=True, verbose_name='adquirido el'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='currency',
            field=models.CharField(blank=True, max_length=3, verbose_name='moneda'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='current_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='valor actual'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='custodian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_of', to='core.party', verbose_name='a cargo de'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='disposed_on',
            field=models.DateField(blank=True, null=True, verbose_name='dado de baja el'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='kind',
            field=models.CharField(db_index=True, max_length=40, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='core.location', verbose_name='ubicación'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=200, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_resources', to='core.party', verbose_name='propietario'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='purchase_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='lo que costó'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='status',
            field=models.CharField(choices=[('planned', 'Planeado'), ('active', 'Activo'), ('suspended', 'Suspendido'), ('disposed', 'Dado de baja')], default='active', max_length=20, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='valuation_date',
            field=models.DateField(blank=True, null=True, verbose_name='valorado el'),
        ),
    ]
