# Generated by Django 5.2.17 on 2026-09-18 17:44

import django.db.models.deletion
import django.db.models.manager
import lares.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_resource_acquired_on_alter_resource_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxItem',
            fields=[
                ('id', models.UUIDField(default=lares.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(choices=[('upload', 'Subido'), ('share', 'Compartido desde el móvil'), ('email', 'Correo'), ('paperless', 'Paperless'), ('watch', 'Carpeta vigilada')], default='upload', max_length=20)),
                ('original_name', models.CharField(blank=True, max_length=300)),
                ('file', models.FileField(blank=True, null=True, upload_to='inbox/%Y/%m/')),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('checksum', models.CharField(db_index=True, max_length=64)),
                ('text', models.TextField(blank=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('new', 'Sin revisar'), ('applied', 'Registrado'), ('discarded', 'Descartado')], default='new', max_length=20)),
                ('applied_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_inbox', to='core.document')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.household')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.UUIDField(default=lares.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('classifier', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=200)),
                ('confidence', models.FloatField(default=0.5)),
                ('plan', models.JSONField(default=dict)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.household')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='core.inboxitem')),
            ],
            options={
                'ordering': ['-confidence'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='inboxitem',
            constraint=models.UniqueConstraint(fields=('household', 'checksum'), name='uniq_inbox_item'),
        ),
    ]
