# Generated by Django 5.2.17 on 2026-09-18 17:53

import django.db.models.deletion
import django.db.models.manager
import lares.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_inboxitem_suggestion_inboxitem_uniq_inbox_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.UUIDField(default=lares.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('key', models.CharField(db_index=True, max_length=40)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('secret_encrypted', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=400)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.household')),
            ],
            options={
                'ordering': ['key'],
                'constraints': [models.UniqueConstraint(fields=('household', 'key', 'label'), name='uniq_connector')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
