# Generated by Django 5.2.17 on 2026-09-18 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_connector'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='disposal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='importe'),
        ),
        migrations.AddField(
            model_name='resource',
            name='disposal_note',
            field=models.CharField(blank=True, max_length=300, verbose_name='nota'),
        ),
        migrations.AddField(
            model_name='resource',
            name='disposal_reason',
            field=models.CharField(blank=True, choices=[('sold', 'Vendido'), ('lost', 'Perdido'), ('stolen', 'Robado'), ('given', 'Regalado'), ('scrapped', 'Desechado'), ('returned', 'Devuelto'), ('transferred', 'Traspasado')], max_length=20, verbose_name='qué pasó'),
        ),
        migrations.AddField(
            model_name='resource',
            name='disposed_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_resources', to='core.party', verbose_name='a quién'),
        ),
        migrations.AddField(
            model_name='resource',
            name='verified_on',
            field=models.DateField(blank=True, null=True, verbose_name='comprobado el'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='status',
            field=models.CharField(choices=[('planned', 'Planeado'), ('active', 'Lo tengo'), ('suspended', 'En pausa'), ('disposed', 'Ya no lo tengo')], default='active', max_length=20, verbose_name='estado'),
        ),
    ]
