# Generated by Django 5.2.17 on 2026-09-18 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0006_resource_disposal_amount_resource_disposal_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='core.party', verbose_name='en dónde o a quién'),
        ),
        migrations.AddField(
            model_name='posting',
            name='beneficiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benefited_postings', to='core.party', verbose_name='para quién'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(db_index=True, verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=models.CharField(max_length=300, verbose_name='concepto'),
        ),
        migrations.AddIndex(
            model_name='posting',
            index=models.Index(fields=['household', 'beneficiary'], name='core_postin_househo_891bd3_idx'),
        ),
    ]
