# Generated by Django 5.2.17 on 2026-09-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_entry_counterparty_posting_beneficiary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='kind',
            field=models.CharField(choices=[('person', 'Persona'), ('organization', 'Organización')], default='person', max_length=20),
        ),
    ]
