# Generated by Django 5.2.17 on 2026-09-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_party_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='calendar_token',
            field=models.CharField(blank=True, db_index=True, max_length=43),
        ),
    ]
