# Generated by Django 5.2.17 on 2026-09-18 19:12

import django.db.models.deletion
import django.db.models.manager
import lares.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_tag_taggeditem_tag_uniq_tag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.UUIDField(default=lares.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('kind', models.CharField(choices=[('contacts', 'Contactos de una etiqueta')], default='contacts', max_length=20, verbose_name='qué se comparte')),
                ('label', models.CharField(max_length=160, verbose_name='cómo lo llamas')),
                ('target', models.CharField(blank=True, max_length=120, verbose_name='alcance')),
                ('token', models.CharField(db_index=True, max_length=43, unique=True)),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='para quién es')),
                ('expires_on', models.DateField(blank=True, null=True, verbose_name='caduca el')),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='veces abierto')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.household')),
            ],
            options={
                'verbose_name': 'enlace compartido',
                'verbose_name_plural': 'enlaces compartidos',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
