# Generated by Django 5.2.17 on 2026-09-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='expires_on',
            field=models.DateField(blank=True, null=True, verbose_name='el acceso caduca el'),
        ),
        migrations.AddField(
            model_name='membership',
            name='invite_token',
            field=models.CharField(blank=True, db_index=True, max_length=43),
        ),
        migrations.AddField(
            model_name='membership',
            name='invited_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
