# Generated by Django 5.2.17 on 2026-09-19 16:56

import django.db.models.deletion
import django.db.models.manager
import lares.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_membresia_con_caducidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='last_seen_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.UUIDField(default=lares.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=160, verbose_name='cómo se llama')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo')),
                ('relationship', models.CharField(blank=True, max_length=80, verbose_name='qué es tuyo')),
                ('sections', models.JSONField(blank=True, default=list, verbose_name='qué incluye')),
                ('note', models.TextField(blank=True, verbose_name='qué quieres que sepa')),
                ('quiet_days', models.PositiveSmallIntegerField(default=60, verbose_name='si no entras en')),
                ('grace_days', models.PositiveSmallIntegerField(default=7, verbose_name='avisar y esperar')),
                ('state', models.CharField(choices=[('armed', 'Armado'), ('warned', 'Avisado'), ('released', 'Liberado'), ('off', 'Desactivado')], default='armed', max_length=12)),
                ('warned_on', models.DateField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('token', models.CharField(blank=True, db_index=True, max_length=43)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='veces abierto')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.household')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_roles', to='core.party')),
            ],
            options={
                'verbose_name': 'contacto de emergencia',
                'verbose_name_plural': 'contactos de emergencia',
                'ordering': ['name'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
