# Generated by Django 5.2.17 on 2026-09-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sucesion_y_emergencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxitem',
            name='external_ref',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddConstraint(
            model_name='inboxitem',
            constraint=models.UniqueConstraint(condition=models.Q(('external_ref__gt', '')), fields=('household', 'external_ref'), name='uniq_inbox_external_ref'),
        ),
    ]
