# Generated by Django 5.2.17 on 2026-09-18 17:08

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.resource')),
                ('make', models.CharField(blank=True, max_length=60)),
                ('model', models.CharField(blank=True, max_length=60)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('vin', models.CharField(blank=True, db_index=True, max_length=24)),
                ('plates', models.CharField(blank=True, db_index=True, max_length=16)),
                ('engine_number', models.CharField(blank=True, max_length=40)),
                ('odometer_km', models.PositiveIntegerField(blank=True, null=True)),
                ('odometer_at', models.DateField(blank=True, null=True)),
                ('avg_km_per_month', models.PositiveIntegerField(blank=True, null=True)),
                ('service_interval_km', models.PositiveIntegerField(blank=True, default=10000, null=True)),
                ('last_service_km', models.PositiveIntegerField(blank=True, null=True)),
                ('last_service_on', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            bases=('core.resource',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
