# Generated by Django 5.2.17 on 2026-09-18 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'vehículo', 'verbose_name_plural': 'vehículos'},
        ),
    ]
