# Generated by Django 5.2.17 on 2026-09-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicle_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='avg_km_per_month',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='kilómetros al mes'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_number',
            field=models.CharField(blank=True, max_length=40, verbose_name='número de motor'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='last_service_km',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='último servicio a los (km)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='last_service_on',
            field=models.DateField(blank=True, null=True, verbose_name='último servicio el'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(blank=True, max_length=60, verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, max_length=60, verbose_name='modelo'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='odometer_at',
            field=models.DateField(blank=True, null=True, verbose_name='kilometraje tomado el'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='odometer_km',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='kilometraje'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plates',
            field=models.CharField(blank=True, db_index=True, max_length=16, verbose_name='placas'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='service_interval_km',
            field=models.PositiveIntegerField(blank=True, default=10000, null=True, verbose_name='servicio cada (km)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(blank=True, db_index=True, max_length=24, verbose_name='número de serie'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='año'),
        ),
    ]
