# Generated by Django 5.2.17 on 2026-09-18 17:31

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.resource')),
                ('last_four', models.CharField(blank=True, max_length=4)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('cut_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('due_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('apr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_card', to='core.account')),
                ('issuer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_cards', to='core.party')),
            ],
            options={
                'verbose_name': 'tarjeta',
                'verbose_name_plural': 'tarjetas',
            },
            bases=('core.resource',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
