# Generated by Django 5.2.17 on 2026-09-18 18:55

import django.db.models.deletion
import django.db.models.manager
import lares.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_household_calendar_token'),
        ('finance', '0002_alter_creditcard_account_alter_creditcard_apr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provision',
            fields=[
                ('id', models.UUIDField(default=lares.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=200, verbose_name='para qué')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='cuánto hace falta')),
                ('saved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='cuánto llevas apartado')),
                ('due_on', models.DateField(blank=True, null=True, verbose_name='para cuándo')),
                ('source_key', models.CharField(blank=True, db_index=True, max_length=200)),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='nota')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisions', to='core.account', verbose_name='en qué cuenta está')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.household')),
            ],
            options={
                'verbose_name': 'provisión',
                'verbose_name_plural': 'provisiones',
                'ordering': ['due_on', 'name'],
                'indexes': [models.Index(fields=['household', 'is_active'], name='finance_pro_househo_9fb18c_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
