# Generated by Django 5.2.17 on 2026-09-18 22:18

import django.db.models.deletion
import django.db.models.manager
import lares.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_share'),
        ('finance', '0004_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.UUIDField(default=lares.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('description', models.CharField(max_length=250, verbose_name='qué compraste')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='total de la compra')),
                ('months', models.PositiveSmallIntegerField(verbose_name='en cuántos meses')),
                ('first_charge_on', models.DateField(verbose_name='primer cargo')),
                ('interest_free', models.BooleanField(default=True, verbose_name='sin intereses')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plans', to='finance.creditcard', verbose_name='con qué tarjeta')),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installment_plans', to='core.entry')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.household')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installment_plans', to='core.party', verbose_name='dónde')),
            ],
            options={
                'verbose_name': 'compra a meses',
                'verbose_name_plural': 'compras a meses',
                'ordering': ['first_charge_on'],
                'indexes': [models.Index(fields=['household', 'card', 'is_active'], name='finance_ins_househo_f07624_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
