# Generated by Django 5.2.17 on 2026-09-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_installmentplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentplan',
            name='installment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='mensualidad que te cobran'),
        ),
    ]
