# Generated by Django 5.2.17 on 2026-09-19 01:09

import django.db.models.deletion
import django.db.models.manager
import lares.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_share'),
        ('finance', '0006_installmentplan_installment_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=lares.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=200, verbose_name='cómo lo llamas')),
                ('kind', models.CharField(choices=[('annual', 'Del año'), ('project', 'De un proyecto')], default='annual', max_length=10, verbose_name='de qué tipo')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ejercicio')),
                ('starts_on', models.DateField(blank=True, null=True, verbose_name='desde')),
                ('ends_on', models.DateField(blank=True, null=True, verbose_name='hasta')),
                ('currency', models.CharField(default='MXN', max_length=3, verbose_name='moneda')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='nota')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.household')),
            ],
            options={
                'verbose_name': 'presupuesto',
                'verbose_name_plural': 'presupuestos',
                'ordering': ['-year', 'name'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PlanLine',
            fields=[
                ('id', models.UUIDField(default=lares.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='previsto')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='nota')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_lines', to='core.account', verbose_name='en qué')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.household')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.plan')),
            ],
            options={
                'verbose_name': 'línea del presupuesto',
                'verbose_name_plural': 'líneas del presupuesto',
                'ordering': ['account__name'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['household', 'is_active'], name='finance_pla_househo_4ff6cc_idx'),
        ),
        migrations.AddConstraint(
            model_name='planline',
            constraint=models.UniqueConstraint(fields=('plan', 'account'), name='uniq_plan_account'),
        ),
    ]
