# Generated by Django 5.2.17 on 2026-09-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_plan_planline_plan_finance_pla_househo_4ff6cc_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planline',
            name='cadence',
            field=models.CharField(choices=[('monthly', 'Al mes'), ('total', 'En todo el periodo')], default='monthly', max_length=10, verbose_name='cada cuánto'),
        ),
    ]
