# Generated by Django 5.2.17 on 2026-09-19 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_topes_a_presupuesto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
