# Generated by Django 5.2.17 on 2026-09-19 01:20

import django.db.models.deletion
import django.db.models.manager
import lares.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_share'),
        ('finance', '0010_quitar_topes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringIncome',
            fields=[
                ('id', models.UUIDField(default=lares.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=200, verbose_name='qué es')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='cuánto te llega')),
                ('cycle', models.CharField(choices=[('weekly', 'Cada semana'), ('biweekly', 'Cada quincena'), ('monthly', 'Cada mes'), ('bimonthly', 'Cada dos meses'), ('quarterly', 'Cada tres meses'), ('semiannual', 'Cada seis meses'), ('yearly', 'Cada año')], default='monthly', max_length=12, verbose_name='cada cuánto')),
                ('pay_day', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='día de pago')),
                ('currency', models.CharField(default='MXN', max_length=3, verbose_name='moneda')),
                ('started_on', models.DateField(blank=True, null=True, verbose_name='desde cuándo')),
                ('ends_on', models.DateField(blank=True, null=True, verbose_name='hasta cuándo')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='nota')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='core.account', verbose_name='dónde entra')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes_categorised', to='core.account', verbose_name='cómo se clasifica')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.household')),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes_paid', to='core.party', verbose_name='quién te paga')),
            ],
            options={
                'verbose_name': 'ingreso recurrente',
                'verbose_name_plural': 'ingresos recurrentes',
                'ordering': ['-amount'],
                'indexes': [models.Index(fields=['household', 'is_active'], name='finance_rec_househo_4e0a0d_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
