# Generated by Django 5.2.17 on 2026-09-19 01:48

import django.db.models.deletion
import django.db.models.manager
import lares.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_share'),
        ('finance', '0011_ingreso_recurrente'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanLineMonth',
            fields=[
                ('id', models.UUIDField(default=lares.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('month', models.PositiveSmallIntegerField(verbose_name='mes')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='previsto ese mes')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.household')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months_set', to='finance.planline')),
            ],
            options={
                'verbose_name': 'mes distinto',
                'verbose_name_plural': 'meses distintos',
                'ordering': ['month'],
                'constraints': [models.UniqueConstraint(fields=('line', 'month'), name='uniq_linea_mes'), models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='mes_valido')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
