# Generated by Django 5.2.17 on 2026-09-18 23:52

import datetime
import django.db.models.deletion
import django.db.models.manager
import lares.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_share'),
        ('finance', '0006_installmentplan_installment_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=lares.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=200, verbose_name='qué quieres')),
                ('kind', models.CharField(choices=[('save', 'Juntar dinero'), ('payoff', 'Dejar de deber')], default='save', max_length=10, verbose_name='de qué tipo')),
                ('target_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='a cuánto quieres llegar')),
                ('target_on', models.DateField(blank=True, null=True, verbose_name='para cuándo')),
                ('currency', models.CharField(default='MXN', max_length=3, verbose_name='moneda')),
                ('baseline_amount', models.DecimalField(decimal_places=2, default=0, help_text='Lo que ya tenías juntado, o lo que debías, al empezar.', max_digits=16, verbose_name='de cuánto partías')),
                ('started_on', models.DateField(default=datetime.date.today, verbose_name='desde cuándo')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='nota')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='core.account', verbose_name='en qué cuenta')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.household')),
                ('provision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='finance.provision', verbose_name='apartado en')),
            ],
            options={
                'verbose_name': 'meta',
                'verbose_name_plural': 'metas',
                'ordering': ['target_on', 'name'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GoalContribution',
            fields=[
                ('id', models.UUIDField(default=lares.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='cuándo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='cuánto')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='nota')),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goal_contributions', to='core.entry')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='goals.goal')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.household')),
            ],
            options={
                'verbose_name': 'aportación',
                'verbose_name_plural': 'aportaciones',
                'ordering': ['-date'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['household', 'is_active'], name='goals_goal_househo_7f74cf_idx'),
        ),
    ]
