# Generated by Django 5.2.17 on 2026-09-18 18:23

import django.db.models.deletion
import django.db.models.manager
import lares.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0007_entry_counterparty_posting_beneficiary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.UUIDField(default=lares.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('title', models.CharField(max_length=200, verbose_name='qué hay que hacer')),
                ('subject_id', models.UUIDField()),
                ('basis', models.CharField(choices=[('time', 'Cada cierto tiempo'), ('usage', 'Cada tantos kilómetros')], default='time', max_length=10, verbose_name='cada qué')),
                ('every_months', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='cada cuántos meses')),
                ('every_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='cada cuántos km')),
                ('last_done_on', models.DateField(blank=True, null=True, verbose_name='última vez')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='coste estimado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.household')),
                ('preferred_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_plans', to='core.party', verbose_name='quién suele hacerlo')),
                ('subject_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_plans', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'plan de mantenimiento',
                'verbose_name_plural': 'planes de mantenimiento',
                'ordering': ['title'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.UUIDField(default=lares.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('title', models.CharField(max_length=200, verbose_name='qué se hizo')),
                ('subject_id', models.UUIDField()),
                ('done_on', models.DateField(db_index=True, verbose_name='cuándo')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='cuánto costó')),
                ('currency', models.CharField(blank=True, max_length=3, verbose_name='moneda')),
                ('odometer_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='kilometraje')),
                ('warranty_until', models.DateField(blank=True, null=True, verbose_name='garantía del trabajo hasta')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.household')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='maintenance.maintenanceplan')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_done', to='core.party', verbose_name='quién lo hizo')),
                ('subject_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'trabajo',
                'verbose_name_plural': 'trabajos',
                'ordering': ['-done_on'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='maintenanceplan',
            index=models.Index(fields=['household', 'subject_type', 'subject_id'], name='maintenance_househo_b8063f_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['household', 'subject_type', 'subject_id', '-done_on'], name='maintenance_househo_858c15_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['household', 'provider'], name='maintenance_househo_fb060c_idx'),
        ),
    ]
