# Generated by Django 5.2.17 on 2026-09-18 18:07

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_resource_disposal_amount_resource_disposal_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.resource')),
                ('property_type', models.CharField(choices=[('house', 'Casa'), ('apartment', 'Departamento'), ('land', 'Terreno'), ('commercial', 'Local comercial'), ('warehouse', 'Bodega'), ('parking', 'Estacionamiento'), ('other', 'Otro')], default='house', max_length=20, verbose_name='tipo')),
                ('tenure', models.CharField(choices=[('owned', 'Propio'), ('co_owned', 'En copropiedad'), ('rented', 'Rentado (soy el inquilino)'), ('borrowed', 'Prestado'), ('usufruct', 'En usufructo'), ('managed', 'Administrado para un tercero')], default='owned', max_length=20, verbose_name='régimen de tenencia')),
                ('use', models.CharField(choices=[('lived_in', 'Lo habito'), ('empty', 'Vacío'), ('rented_out', 'Lo tengo rentado'), ('for_sale', 'En venta'), ('lent', 'Prestado a alguien'), ('other', 'Otro')], default='lived_in', max_length=20, verbose_name='uso')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='dirección')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='ciudad')),
                ('subdivision', models.CharField(blank=True, max_length=10, verbose_name='estado')),
                ('land_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='superficie del terreno (m²)')),
                ('built_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='construcción (m²)')),
                ('cadastral_id', models.CharField(blank=True, max_length=60, verbose_name='clave catastral')),
                ('deed_number', models.CharField(blank=True, max_length=60, verbose_name='escritura')),
                ('deed_date', models.DateField(blank=True, null=True, verbose_name='fecha de escritura')),
                ('ownership_share', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='tu parte (%)')),
                ('predial_month', models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='mes del predial')),
                ('predial_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='predial estimado')),
                ('rent_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='renta que pagas')),
                ('rent_due_day', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='día de pago')),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='depósito en garantía')),
                ('lease_ends_on', models.DateField(blank=True, null=True, verbose_name='el contrato acaba el')),
                ('landlord', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rented_out_to_us', to='core.party', verbose_name='arrendador')),
            ],
            options={
                'verbose_name': 'inmueble',
                'verbose_name_plural': 'inmuebles',
            },
            bases=('core.resource',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.resource')),
                ('service_kind', models.CharField(choices=[('water', 'Agua'), ('power', 'Electricidad'), ('gas', 'Gas'), ('internet', 'Internet'), ('phone', 'Teléfono'), ('waste', 'Recolección'), ('hoa', 'Cuota de condominio'), ('security', 'Seguridad'), ('other', 'Otro')], default='other', max_length=20, verbose_name='servicio')),
                ('contract_number', models.CharField(blank=True, max_length=60, verbose_name='número de contrato')),
                ('cycle', models.CharField(choices=[('monthly', 'Cada mes'), ('bimonthly', 'Cada dos meses'), ('quarterly', 'Cada tres meses'), ('yearly', 'Cada año')], default='monthly', max_length=20, verbose_name='periodicidad')),
                ('due_day', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='día de pago')),
                ('typical_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='importe habitual')),
                ('property_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='property.property', verbose_name='del inmueble')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_provided', to='core.party', verbose_name='proveedor')),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
            },
            bases=('core.resource',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
