# Generated by Django 5.2.17 on 2026-09-18 23:31

from django.db import migrations


class Migration(migrations.Migration):

    # Los campos se borran solo despues de que leases los haya copiado: al
    # reves, la migracion de datos leeria columnas que ya no existen.
    dependencies = [
        ("leases", "0002_migrar_rentas_de_property"),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='deposit_amount',
        ),
        migrations.RemoveField(
            model_name='property',
            name='landlord',
        ),
        migrations.RemoveField(
            model_name='property',
            name='lease_ends_on',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rent_amount',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rent_due_day',
        ),
    ]
