# Generated by Django 5.2.17 on 2026-09-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_remove_property_deposit_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='use',
            field=models.CharField(choices=[('lived_in', 'Lo habito'), ('empty', 'Vacío'), ('rented_out', 'Se lo rento a un inquilino'), ('for_sale', 'En venta'), ('lent', 'Prestado a alguien'), ('other', 'Otro')], default='lived_in', max_length=20, verbose_name='uso'),
        ),
    ]
