# Generated by Django 5.2.17 on 2026-09-18 18:05

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_resource_disposal_amount_resource_disposal_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Belonging',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.resource')),
                ('category', models.CharField(choices=[('appliance', 'Electrodoméstico'), ('electronics', 'Electrónica'), ('tool', 'Herramienta'), ('sports', 'Deporte y bicicletas'), ('instrument', 'Instrumento musical'), ('jewelry', 'Joyería y relojes'), ('art', 'Arte y coleccionables'), ('furniture', 'Mobiliario'), ('other', 'Otro')], default='other', max_length=20, verbose_name='categoría')),
                ('brand', models.CharField(blank=True, max_length=80, verbose_name='marca')),
                ('model_name', models.CharField(blank=True, max_length=80, verbose_name='modelo')),
                ('serial_number', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='número de serie')),
                ('warranty_until', models.DateField(blank=True, null=True, verbose_name='garantía hasta')),
                ('warranty_note', models.CharField(blank=True, max_length=200, verbose_name='qué cubre la garantía')),
                ('appraised_value', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='valor de avalúo')),
                ('appraised_on', models.DateField(blank=True, null=True, verbose_name='avalúo del')),
            ],
            options={
                'verbose_name': 'objeto',
                'verbose_name_plural': 'objetos',
            },
            bases=('core.resource',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
