# Generated by Django 5.2.17 on 2026-09-18 18:50

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_household_calendar_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.resource')),
                ('service_kind', models.CharField(choices=[('streaming', 'Streaming y entretenimiento'), ('software', 'Software y apps'), ('hosting', 'Servidores y dominios'), ('cloud', 'Almacenamiento en la nube'), ('telecom', 'Telefonía e internet'), ('gym', 'Gimnasio y salud'), ('media', 'Prensa y suscripciones'), ('membership', 'Membresías y clubes'), ('other', 'Otro')], default='other', max_length=20, verbose_name='tipo')),
                ('plan', models.CharField(blank=True, max_length=120, verbose_name='plan')),
                ('cycle', models.CharField(choices=[('weekly', 'Cada semana'), ('monthly', 'Cada mes'), ('quarterly', 'Cada tres meses'), ('semiannual', 'Cada seis meses'), ('yearly', 'Cada año')], default='monthly', max_length=20, verbose_name='cada cuánto se cobra')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='importe del cargo')),
                ('charge_day', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='día del cargo')),
                ('access', models.CharField(choices=[('mine', 'La cuenta es mía'), ('shared', 'Compartida en la familia'), ('theirs', 'Es de otra persona, yo solo la pago')], default='mine', max_length=20, verbose_name='de quién es la cuenta')),
                ('started_on', models.DateField(blank=True, null=True, verbose_name='desde cuándo')),
                ('commitment_until', models.DateField(blank=True, null=True, verbose_name='permanencia hasta')),
                ('cancel_url', models.URLField(blank=True, max_length=400, verbose_name='cómo se cancela')),
                ('previous_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='importe anterior')),
                ('price_changed_on', models.DateField(blank=True, null=True, verbose_name='cambió de precio el')),
                ('account_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions_held', to='core.party', verbose_name='a nombre de quién está')),
                ('paid_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='core.account', verbose_name='con qué se paga')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions_sold', to='core.party', verbose_name='a quién se lo pagas')),
            ],
            options={
                'verbose_name': 'suscripción',
                'verbose_name_plural': 'suscripciones',
            },
            bases=('core.resource',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
