# Generated by Django 5.2.17 on 2026-09-19 00:48

import datetime
import django.db.models.deletion
import django.db.models.manager
import lares.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_share'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxProfile',
            fields=[
                ('id', models.UUIDField(default=lares.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('regime', models.CharField(choices=[('salaries', 'Sueldos y salarios'), ('resico', 'RESICO (simplificado de confianza)'), ('business', 'Actividad empresarial y profesional'), ('lease', 'Arrendamiento'), ('platforms', 'Plataformas tecnológicas'), ('other', 'Otro')], default='salaries', max_length=20, verbose_name='régimen')),
                ('rfc', models.CharField(blank=True, max_length=13, verbose_name='RFC')),
                ('started_on', models.DateField(blank=True, null=True, verbose_name='desde cuándo')),
                ('uma_annual', models.DecimalField(blank=True, decimal_places=2, help_text='El SAT la publica cada febrero. Sin ella no se aplica ese tope.', max_digits=12, null=True, verbose_name='UMA anual del ejercicio')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='nota')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.household')),
                ('taxpayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_profiles', to='core.party', verbose_name='quién declara')),
            ],
            options={
                'verbose_name': 'perfil fiscal',
                'verbose_name_plural': 'perfiles fiscales',
                'ordering': ['taxpayer__name'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Filing',
            fields=[
                ('id', models.UUIDField(default=lares.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('kind', models.CharField(choices=[('monthly', 'Pago provisional mensual'), ('annual', 'Declaración anual'), ('diot', 'DIOT'), ('other', 'Otra')], default='monthly', max_length=10, verbose_name='qué declaración')),
                ('period', models.CharField(max_length=7, verbose_name='periodo')),
                ('filed_on', models.DateField(blank=True, null=True, verbose_name='presentada el')),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='lo que pagaste')),
                ('balance_favor', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='saldo a favor')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='nota')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.household')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filings', to='core.document', verbose_name='acuse')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filings', to='taxes.taxprofile', verbose_name='de quién')),
            ],
            options={
                'verbose_name': 'declaración',
                'verbose_name_plural': 'declaraciones',
                'ordering': ['-period'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'kind', 'period'), name='uniq_declaracion_periodo')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.UUIDField(default=lares.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('kind', models.CharField(choices=[('medical', 'Médicos, dentales y hospitalarios'), ('medical_insurance', 'Seguro de gastos médicos'), ('funeral', 'Gastos funerarios'), ('donation', 'Donativos'), ('mortgage', 'Intereses reales de hipoteca'), ('retirement', 'Aportaciones para el retiro'), ('tuition', 'Colegiaturas'), ('school_transport', 'Transporte escolar obligatorio'), ('savings', 'Depósitos en cuentas para el ahorro'), ('business', 'Gasto deducible de la actividad')], default='medical', max_length=24, verbose_name='de qué tipo')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='concepto')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='importe')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='fecha')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='nota')),
                ('beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deductions_received', to='core.party', verbose_name='a nombre de quién')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deductions', to='core.document', verbose_name='con qué factura')),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deductions', to='core.entry', verbose_name='qué movimiento')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.household')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='taxes.taxprofile', verbose_name='de quién')),
            ],
            options={
                'verbose_name': 'deducción',
                'verbose_name_plural': 'deducciones',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['household', 'date'], name='taxes_deduc_househo_1fe8b1_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('document__isnull', False)), fields=('profile', 'document'), name='uniq_deduccion_documento')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Withholding',
            fields=[
                ('id', models.UUIDField(default=lares.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('kind', models.CharField(choices=[('isr', 'ISR'), ('iva', 'IVA')], default='isr', max_length=5, verbose_name='qué impuesto')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='importe retenido')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='fecha')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='nota')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withholdings', to='core.document', verbose_name='con qué comprobante')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.household')),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withholdings_made', to='core.party', verbose_name='quién retuvo')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withholdings', to='taxes.taxprofile', verbose_name='de quién')),
            ],
            options={
                'verbose_name': 'retención',
                'verbose_name_plural': 'retenciones',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['household', 'date'], name='taxes_withh_househo_d3dcb5_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
