# Generated by Django 5.2.17 on 2026-09-18 23:30

import django.db.models.deletion
import django.db.models.manager
import lares.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_share'),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.resource')),
                ('direction', models.CharField(choices=[('landlord', 'Lo rento a alguien'), ('tenant', 'Se lo rento a alguien')], default='landlord', max_length=10, verbose_name='sentido')),
                ('starts_on', models.DateField(verbose_name='desde')),
                ('ends_on', models.DateField(blank=True, null=True, verbose_name='hasta')),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='renta mensual')),
                ('rent_day', models.PositiveSmallIntegerField(default=1, verbose_name='día de pago')),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='depósito en garantía')),
                ('deposit_returned_on', models.DateField(blank=True, null=True, verbose_name='depósito devuelto el')),
                ('deposit_returned_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='devuelto')),
                ('increase_kind', models.CharField(choices=[('none', 'Sin incremento pactado'), ('percent', 'Un porcentaje fijo'), ('inpc', 'Según la inflación (INPC)')], default='none', max_length=10, verbose_name='incremento anual')),
                ('increase_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='porcentaje')),
                ('increase_month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='mes del incremento')),
                ('legal_policy', models.CharField(blank=True, max_length=160, verbose_name='póliza jurídica')),
                ('counterpart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leases', to='core.party', verbose_name='con quién')),
                ('guarantor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leases_guaranteed', to='core.party', verbose_name='fiador')),
                ('property_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='property.property', verbose_name='de qué inmueble')),
            ],
            options={
                'verbose_name': 'contrato de arrendamiento',
                'verbose_name_plural': 'contratos de arrendamiento',
            },
            bases=('core.resource',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RentPayment',
            fields=[
                ('id', models.UUIDField(default=lares.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('period', models.CharField(db_index=True, max_length=7, verbose_name='periodo')),
                ('due_on', models.DateField(verbose_name='vencía el')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='lo que tocaba')),
                ('paid_on', models.DateField(blank=True, null=True, verbose_name='pagado el')),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='lo que se pagó')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='nota')),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent_payments', to='core.entry')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.household')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='leases.lease')),
            ],
            options={
                'verbose_name': 'mes de renta',
                'verbose_name_plural': 'meses de renta',
                'ordering': ['-due_on'],
                'constraints': [models.UniqueConstraint(fields=('lease', 'period'), name='uniq_rent_period')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
