# Generated by Django 5.2.17 on 2026-09-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0002_migrar_rentas_de_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='direction',
            field=models.CharField(choices=[('landlord', 'Es mío y se lo rento a alguien'), ('tenant', 'No es mío, yo pago la renta')], default='landlord', max_length=10, verbose_name='sentido'),
        ),
    ]
