# Generated by Django 5.2.17 on 2026-09-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0003_etiquetas_de_sentido'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='tracked_from',
            field=models.DateField(blank=True, null=True, verbose_name='llevar el control desde'),
        ),
    ]
